// Game constants - all configurable game values (sizes, speeds, points, etc.).
import { mobileAndTabletcheck } from "./utils.js";

// Cache mobile detection result (device type doesn't change during gameplay)
export const IS_MOBILE = mobileAndTabletcheck();

// Key code constants
export const Keys = {
	SPACE: 32,
	LEFT: 37,
	UP: 38,
	RIGHT: 39,
	P: 80,
	ESCAPE: 27,
};

export const Constants = {
	SCR_WIDTH: 1100,
	SCR_HEIGHT: 620,
	MOB_BUTTON_SIZE: 100,

	SHIPS: 3,

	WAVE_START: 1,
	WAVE_INC: 1,

	SHIP_RADIUS: 15,
	SHIP_ROTATIONSPEED: 0.25,
	SHIP_ACCELERATION: 0.008,
	SHIP_MAXVELOCITY: 4.0,
	SHIP_IMMUME: 4.0,

	BULLET_FIRESPEED: 250,
	BULLET_RADIUS: 4,
	BULLET_LIFETIME: 500,
	BULLET_ACCELERATION: 1.0,
	BULLET_DRAW_OFFSET: 2,

	EXPLOSION_ACCELERATION: 0.5,
	EXPLOSION_PART_RADIUS: 2.0,
	EXPLOSION_DRAW_OFFSET: 2,
	EXPLOSION: {
		SHIP: { particles: 75, lifetime: 300, vibrate: 100 },
		BULLET: { particles: 10, lifetime: 100, vibrate: 0 },
		ASTEROID_MULTIPLIER: { particles: 50, lifetime: 120 },
	},

	ASTEROID: [
		{
			RADIUS: 40,
			ACCELERATION: 0.02,
			HITS: 7,
			POINTCOUNT: 15,
			POINTS: 1000,
		},
		{
			RADIUS: 25,
			ACCELERATION: 0.04,
			HITS: 3,
			POINTCOUNT: 15,
			POINTS: 500,
		},
		{
			RADIUS: 15,
			ACCELERATION: 0.06,
			HITS: 1,
			POINTCOUNT: 15,
			POINTS: 250,
		},
	],
	ASTEROID_SPAWN_COUNT: 3,
	ASTEROID_SPAWN_OFFSET_MIN: -15,
	ASTEROID_SPAWN_OFFSET_MAX: 30,
	ASTEROID_START_SCREEN_COUNT: 20,

	UI: {
		TOP_MARGIN: 10,
		LINE_HEIGHT: 35,
		TEXT_SIZE: 40,
		BOX_WIDTH_MAX: 725,
		BOX_WIDTH_RATIO: 0.8,
		BOX_HEIGHT_MAX: 250,
		BOX_HEIGHT_RATIO: 0.5,
		BOX_STROKE_WIDTH: 3,
		BUTTON_MARGIN: 5,
		BUTTON_SPACING: 10,
		HUD_SCORE_SIZE: 48,
		HUD_SHIP_ICON_SIZE: 1.2,
		HUD_SHIP_SPACING: 40,
	},
	TEXT_OFFSET: {
		TOP: -55,
		CENTER: 0,
		BOTTOM: 55,
		SMALL_OFFSET: -27.5,
		SMALL_OFFSET_POS: -27.5,
	},

	TIMERS: {
		RESIZE_THROTTLE: 100,
		ORIENTATION_DELAY: 200,
		BLINK_INTERVAL: 250,
		IMMUNE_INTERVAL: 1000,
		WAVE_COUNTDOWN: 1000,
		PRESS_SPACE_BLINK: 800,
	},

	MATH: {
		FULL_CIRCLE_DEG: 360,
		MAX_ASTEROID_TYPE: 2,
		FRAME_TIME_MAX: 100,
	},

	COLLISION: {
		MIN_DISTANCE_SQ: 0.01,
		FALLBACK_DISTANCE: 0.1,
		PUSH_FACTOR: 0.5,
		SEPARATION_EXTRA: 1,
	},

	SCREEN_WRAP_MARGIN: 5,

	START_TEXT: "hit space to start",
	CONTINUE_TEXT: "hit space to continue",

	BUTTON_IDOL_OPACITY: 0.4,
	BUTTON_PRESSED_OPACITY: 0.8,
};

if (IS_MOBILE) {
	Constants.START_TEXT = "tap to start game";
	Constants.CONTINUE_TEXT = "tap to continue";
}
